from enum import Enum

class AccountStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DORMANT = "DORMANT"
    PRIMARY = "PRIMARY"
    CLOSED = "CLOSED"
    DEBIT_TRANSACTION_BLOCKED = "DEBIT_TRANSACTION_BLOCKED"
    CREDIT_TRANSACTION_BLOCKED = "CREDIT_TRANSACTION_BLOCKED"
    ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED"